### ISSUE TITLE
Abgabe nach vollständigem Ausfüllen nicht möglich

### ISSUE THREAD

**Issue by bkleinen** [digitalservicebund/grundsteuer#685]
Bitte prüfen oder ergänzen Sie Ihre Angaben.
Feld '$/Vorsatz[1]/Aktenzeichen[1]$': Sie haben ein ungültiges Aktenzeichen angegeben.

**Comment by frederike-ramin** [comment]
Vielen Dank für die Einreichung des Issues. Sie haben vollkommen recht, die Fehlermeldung ist nicht sehr eindeutig formuliert. Wir haben die Fehlermeldung angepasst, was es für Sie leichter machen sollte, den Fehler zu beheben. 
Kurz formuliert: Es liegt ein formales Problem mit dem angegebenen Aktenzeichen des Grundstücks vor. Um dies zu korrigieren, ändern Sie Ihre Eingabe unter Grundstück > Aktenzeichen / Steuernummer.

Implemented in [Improve Aktenzeichen error message](https://github.com/digitalservicebund/grundsteuer/commit/70c11e24cf5e450a0c2088f87e543788b1f72413)
